// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeDomainLibrary.Models;

#nullable disable

namespace TreeStructureWebApi.Migrations
{
    [DbContext(typeof(OfficeContext))]
    [Migration("20240610102612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TreeStructureWebApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = "JD001",
                            JobTitle = "Founder",
                            Name = "John Doe",
                            Role = 4
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = "JS002",
                            JobTitle = "Director",
                            Name = "Jane Smith",
                            ParentId = 1,
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = "BJ003",
                            JobTitle = "Manager",
                            Name = "Bob Johnson",
                            ParentId = 2,
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = "AB004",
                            JobTitle = "Team Lead",
                            Name = "Alice Brown",
                            ParentId = 3,
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = "MD005",
                            JobTitle = "Team Employee",
                            Name = "Mike Davis",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = "EC006",
                            JobTitle = "Software Engineer",
                            Name = "Emily Chen",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = "DL007",
                            JobTitle = "QA Engineer",
                            Name = "David Lee",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = "ST008",
                            JobTitle = "DevOps Engineer",
                            Name = "Sarah Taylor",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = "KW009",
                            JobTitle = "Product Manager",
                            Name = "Kevin White",
                            ParentId = 2,
                            Role = 2
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = "LN010",
                            JobTitle = "UX Designer",
                            Name = "Lisa Nguyen",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = "MP011",
                            JobTitle = "Backend Engineer",
                            Name = "Michael Patel",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = "RK012",
                            JobTitle = "Frontend Engineer",
                            Name = "Rachel Kim",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = "CH013",
                            JobTitle = "Full Stack Engineer",
                            Name = "Christopher Hall",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = "JM014",
                            JobTitle = "Data Scientist",
                            Name = "Jessica Martin",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = "BT015",
                            JobTitle = "Data Analyst",
                            Name = "Brian Thompson",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = "OW016",
                            JobTitle = "Marketing Manager",
                            Name = "Olivia Walker",
                            ParentId = 2,
                            Role = 2
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = "AB017",
                            JobTitle = "Marketing Specialist",
                            Name = "Alexander Brown",
                            ParentId = 16,
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = "SL018",
                            JobTitle = "Sales Manager",
                            Name = "Samantha Lee",
                            ParentId = 2,
                            Role = 2
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = "JK019",
                            JobTitle = "Sales Representative",
                            Name = "Julia Kim",
                            ParentId = 18,
                            Role = 0
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = "DP020",
                            JobTitle = "Customer Support",
                            Name = "Daniel Patel",
                            ParentId = 18,
                            Role = 0
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = "JL021",
                            JobTitle = "Software Engineer",
                            Name = "Jacob Lee",
                            ParentId = 3,
                            Role = 0
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = "JC022",
                            JobTitle = "QA Engineer",
                            Name = "Jasmine Chen",
                            ParentId = 3,
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = "JW023",
                            JobTitle = "DevOps Engineer",
                            Name = "Jordan White",
                            ParentId = 3,
                            Role = 0
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = "JB024",
                            JobTitle = "Team Lead",
                            Name = "Jessica Brown",
                            ParentId = 3,
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = "JD025",
                            JobTitle = "Team Employee",
                            Name = "James Davis",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = "JC026",
                            JobTitle = "Software Engineer",
                            Name = "Jennifer Chen",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = "JL027",
                            JobTitle = "QA Engineer",
                            Name = "Joseph Lee",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = "JT028",
                            JobTitle = "DevOps Engineer",
                            Name = "Julia Taylor",
                            ParentId = 4,
                            Role = 0
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = "JW029",
                            JobTitle = "Product Manager",
                            Name = "Jonathan White",
                            ParentId = 2,
                            Role = 2
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = "JB030",
                            JobTitle = "UX Designer",
                            Name = "Jacqueline Brown",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 31,
                            EmployeeId = "JD031",
                            JobTitle = "Backend Engineer",
                            Name = "Joshua Davis",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 32,
                            EmployeeId = "JK032",
                            JobTitle = "Frontend Engineer",
                            Name = "Jessica Kim",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 33,
                            EmployeeId = "JH033",
                            JobTitle = "Full Stack Engineer",
                            Name = "Joseph Hall",
                            ParentId = 9,
                            Role = 0
                        },
                        new
                        {
                            Id = 34,
                            EmployeeId = "JM034",
                            JobTitle = "Data Scientist",
                            Name = "Jennifer Martin",
                            ParentId = 9,
                            Role = 0
                        });
                });

            modelBuilder.Entity("TreeStructureWebApi.Models.Employee", b =>
                {
                    b.HasOne("TreeStructureWebApi.Models.Employee", "Parent")
                        .WithMany("DirectReports")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeStructureWebApi.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");
                });
#pragma warning restore 612, 618
        }
    }
}
